apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mern-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Latha1722/aws-eks-project3.git
    targetRevision: main
    path: k8s-deployments
  destination:
    server: https://kubernetes.default.svc
    namespace: mern-microservices
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
