apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-deployment
  namespace: mern-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
        - name: product-container
          image: 466825169909.dkr.ecr.ap-south-1.amazonaws.com/product-service:e81de7a6356b15bf5724571d1964def37d57a5f8
          ports:
            - containerPort: 5002
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: MONGO_URI
