apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-install-info
  namespace: argocd
data:
  info: |
    Install ArgoCD using official manifest:

    kubectl apply -n argocd \
      -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
