apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mern-dev
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/Latha1722/aws-eks-project3.git
    targetRevision: main
    path: k8s-deployments
    recurse: true

  destination:
    server: https://kubernetes.default.svc
    namespace: mern-dev

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

