apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
  namespace: mern-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - name: user-container
          image: 466825169909.dkr.ecr.ap-south-1.amazonaws.com/user-service:latest
          ports:
            - containerPort: 5002
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: MONGO_URI
