apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: mern-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend-container
          image: 466825169909.dkr.ecr.ap-south-1.amazonaws.com/frontend:680950d39f2c49dbe2d687745561dc4049c99fe9
          ports:
            - containerPort: 3000
