apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: mern-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend-container
          image: 466825169909.dkr.ecr.ap-south-1.amazonaws.com/frontend:bc488560a8a20bd0baab35bbd6cb2388c19e9f37
          ports:
            - containerPort: 3000
