apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: mern-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend-container
          image: 466825169909.dkr.ecr.ap-south-1.amazonaws.com/frontend:d8dc46649fd226a72f26b9cabe696b8e90212adb
          ports:
            - containerPort: 3000
