apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
  namespace: mern-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth-container
          image: 466825169909.dkr.ecr.ap-south-1.amazonaws.com/auth-service:8844dfabaef2a3f6564c13fd19195b7841df1a5e
          ports:
            - containerPort: 5001
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: MONGO_URI
