name: Build and Deploy Frontend

# on:
#   push:
#     branches:
#       - main
#     paths:
#       - 'frontend/**'
#       - 'k8s-deployments/frontend/**'

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
      - 'k8s-deployments/frontend/**'

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  EKS_CLUSTER_NAME: ${{ secrets.EKS_CLUSTER_NAME }}

jobs:
  frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region $AWS_REGION | \
          docker login --username AWS --password-stdin \
          $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com

      - name: Build Docker image
        run: |
          docker build -t frontend ./frontend

      - name: Tag Docker image
        run: |
          docker tag frontend:latest \
          $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/frontend:latest

      - name: Push Docker image to ECR
        run: |
          docker push \
          $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/frontend:latest

      - name: Update kubeconfig for EKS
        run: |
          aws eks update-kubeconfig \
          --region $AWS_REGION \
          --name $EKS_CLUSTER_NAME

    
      - name: Deploy Kubernetes Resources
        run: |
          kubectl apply -f k8s-deployments/namespace.yaml
          kubectl apply -f k8s-deployments/frontend/deployment.yaml
          kubectl apply -f k8s-deployments/frontend/service.yaml

      - name: Install AWS Load Balancer Controller
        run: |
          helm repo add eks https://aws.github.io/eks-charts
          helm repo update

          helm upgrade --install aws-load-balancer-controller eks/aws-load-balancer-controller \
            -n kube-system \
            --set clusterName=${{ secrets.EKS_CLUSTER_NAME }} \
            --set serviceAccount.create=true \
            --set serviceAccount.name=aws-load-balancer-controller \
            --set serviceAccount.annotations."eks\.amazonaws\.com/role-arn"=arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/aws-load-balancer-controller

      - name: Apply ingress
        run: |
          kubectl apply -f k8s-deployments/ingress.yaml -n mern-microservices

      - name: Wait for pods to start
        run: sleep 40

      - name: Check status
        run: |
          echo "=== Pods ==="
          kubectl get pods -n mern-microservices

          echo "=== Ingress URL ==="
          kubectl get ingress -n mern-microservices

          echo "=== Load Balancer Controller pods ==="
          kubectl get pods -n kube-system | grep aws-load-balancer

          echo "=== Ingress status ==="
          kubectl get ingress -n mern-microservices

          echo "=== Ingress details ==="
          kubectl describe ingress mern-ingress -n mern-microservices
