name: Build and Deploy Frontend

# on:
#   push:
#     branches:
#       - main
#     paths:
#       - 'frontend/**'
#       - 'k8s-deployments/frontend/**'

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
      - 'k8s-deployments/frontend/**'

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  EKS_CLUSTER_NAME: ${{ secrets.EKS_CLUSTER_NAME }}

jobs:
  frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region $AWS_REGION | \
          docker login --username AWS --password-stdin \
          $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com

      - name: Build Docker image
        run: |
          docker build -t frontend ./frontend

      - name: Tag Docker image
        run: |
          docker tag frontend:latest \
          $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/frontend:latest

      - name: Push Docker image to ECR
        run: |
          docker push \
          $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/frontend:latest

      - name: Update kubeconfig for EKS
        run: |
          aws eks update-kubeconfig \
          --region $AWS_REGION \
          --name $EKS_CLUSTER_NAME

    
      - name: Deploy Kubernetes Resources
        run: |
          kubectl apply -f k8s-deployments/namespace.yaml
          kubectl apply -f k8s-deployments/frontend/deployment.yaml
          kubectl apply -f k8s-deployments/frontend/service.yaml
